title: Security Blogs
author: Kent Bayron
email: bayronkentoy@gmail.com 
url: https://kentslaves.github.io
description: Join me on my thrilling hacking adventures. Learn about my experiences and findings in the realm of cybersecurity, all shared for fun.
favicon: "./favicon.ico"

moving:
  avatar_url: avatar.jpg
  about_you: bug bounty hunter x penetration tester 
  date_format: "%b %d" 
  back_to: "Index"

  social_links:
    twitter: test
    facebook: test

remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag
