title: Security Blogs
author: Kent Bayron
email: bayronkentoy@gmail.com 
url: https://kentslaves.github.io
description: A clean and minimalist theme for Jekyll.
favicon: "./favicon.ico"

moving:
  avatar_url: avatar.jpg
  about_you: bug bounty hunter | penetration tester 
  date_format: "%b %d" 
  back_to: "Index"

  social_links:
    twitter: test
    github: test
    rss: RSS
    facebook: test
    linkedin: test
    bugcrowd: https://bugcrowd.com/kentslaves

remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
  - jekyll-seo-tag
